Exhibits/urls.py
from django.conf.urls import url
from django.conf.urls import include
from . import views

app_name = 'exhibits'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^exhibits/$', views.IndexView.as_view(), name='index'),
    url(r'^exhibits/(?P<pk>[0-9]+)$', views.DetailView.as_view(), name='detail'),
    url(r'^search?$', views.search, name='search')
]

Exhibits/models.py
from django.db import models


# Create your models here.

class Exhibit(models.Model):
    exhibit_title = models.CharField(max_length=200)
    exhibit_description = models.TextField()
    exhibit_picture = models.ImageField(upload_to="gallery")
    

Exhibits/views.py
from django.views import generic
from django.shortcuts import render, redirect
from .models import Exhibit
from django.contrib.postgres.search import SearchVector, SearchQuery
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


#We don't have a home page yet so this redirects our TLD to index
def home(request):
    return redirect('/exhibits/')

#lists all items in DB
class IndexView(generic.ListView):
    template_name = 'exhibits/index.html'
    paginate_by = 5 # number of results per page

    def get_queryset(self):
        return Exhibit.objects.all()

#provides details on a specific item in the db
class DetailView(generic.DetailView):
    model = Exhibit
    template_name = 'exhibits/detail.html'

#handles our search queries
def search(request):
    exhibits_list = Exhibit.objects.all()
    query = request.GET.get('q')

    if query:
        exhibits_list = Exhibit.objects.annotate(
        search=SearchVector('exhibit_title') + SearchVector('exhibit_description'),
        ).filter(search = SearchQuery(query) & SearchQuery(query))

    paginator = Paginator(exhibits_list,5) #5 results per page
    page = request.GET.get('page')

    try:
        exhibits = paginator.page(page)
    except PageNotAnInteger:
        exhibits = paginator.page(1)
    except EmptyPage:
        exhibits = paginator.page(paginator.num_pages)

    context = dict(results = exhibits, q = query)
    return render(request, "exhibits/results.html", context)
    

Exhibits/templates/exhibits/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <!-- Loads path to static files-->
        {% load static %}

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'exhibits/style.css' %}">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
    <body>
        <!-- boostrap navbar-->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    
                    <!--Hamburger button for small screens-->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!--Home / Logo-->
                    <a class="navbar-brand" href="{% url 'exhibits:index'%}">Active Exhibits</a>  
                </div>
                <!--Items-->
                <div class="collapse navbar-collapse" id="topNavBar">
                    <ul class="nav navbar-nav">
                        <!--<li> items in here-->
                    </ul>
        
                    <!--split where right-loaded entries exist in navbar-->
                    <ul class="nav navbar-nav nav navbar-right">
                        <!--This is the search bar-->
                        <form class="navbar-form navbar-left" role="search" method="GET" action="search">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}" placeholder="Search...">
                            </div>
                            <button type="submit" class="btn btn-default">Search</button>
                        </form>
                    </ul>
                </div>
            </div>
        </nav>
    {% block body %}
    {% endblock %}
    </body>

</html>

Exhibits/templates/exhibits/detail.html
{% extends 'exhibits/base.html' %}
{% block title %} Item Details {% endblock %}
{% block body %}

    <h1>
        {{ exhibit.exhibit_title }}
    </h1>

    <div class="row">
        <div class="col-md-6 col-xs-12" style="background-color: #233343">
            <img src="{{ exhibit.exhibit_picture.url }}" class="img-responsive"></img>          
        </div>
        <div class="col-md-6 col-xs-12" style="background-color: #233343">
            <p>{{ exhibit.exhibit_description }}</p>
        </div>
    </div>


</div>

{% endblock %}

Exhibits/templates/exhibits/index.html
{% extends 'exhibits/base.html' %}
{% block title %} Museum Index {% endblock %}
{% block body %}

    <!--Landing-wrapper includes our background, most page elements are within it-->

    <div class="container-fluid">
        {% if exhibit_list %}
            <ul>
                {% for exhibit in exhibit_list %}
                    <div class="row">
                        <div class="col-md-6 col-xs-12" style="background-color: #233343">
                            <h3><a href="{% url 'exhibits:detail' exhibit.id %}">{{ exhibit.exhibit_title }}</a></h3>
                            <p>{{ exhibit.exhibit_description }}</p>
                        </div>     
                        <div class="col-md-6 col-xs-12"style="background-color: #233343">
                            <img src="{{ exhibit.exhibit_picture.url }}" class="img-responsive"></img>
                        </div>                     
                    </div>
                    <br/>
                {% endfor %}
            </ul>

            {% if is_paginated %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
	            </ul>
	        {% endif %}

        {% else %}
                <p>No Exhibits are active right now</p>
        {% endif %}
    </div>




{% endblock %}

Exhibits/templates/exhibits/results.html
{% extends 'exhibits/base.html' %}
{% block title %} Museum Index {% endblock %}
{% block body %}

<div class="container-fluid">
        {% if results %}
            <ul>
                {% for exhibit in results %}
                    <div class="row">
                        <div class="col-md-6 col-xs-12" style="background-color: #233343">
                            <h3><a href="{% url 'exhibits:detail' exhibit.id %}">{{ exhibit.exhibit_title }}</a></h3>
                            <p>{{ exhibit.exhibit_description }}</p>
                        </div>     
                        <div class="col-md-6 col-xs-12"style="background-color: #233343">
                            <img src="{{ exhibit.exhibit_picture.url }}" class="img-responsive"></img>
                        </div>                     
                    </div>
                    <br/>
                {% endfor %}
            </ul>

            {% if results.has_other_pages %}
                <ul class="pagination">
                    {% if results.has_previous %}
                        <li><a href="?page={{ results.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if results.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if results.has_next %}
                        <li><a href="?page={{ results.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
	            </ul>
	        {% endif %}

        {% else %}
                <p>Your search of {{q}} returned no results</p>
        {% endif %}
    </div>

{% endblock %}